services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=qwerty123'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=root'
    ports:
      - '3306'